const express = require('express')
const router = express.Router()
const authRouter = require('./auth.routes')
const productRouter = require('./product.routes')
const categoryRouter = require('./category.routes')
const brandRouter = require('./brand.routes')
const userRouter = require('./user.routes')
const ReviewRouter = require('./review.routes')
const CartRouter = require('./cart.routes')
const salesRouter = require('./sale.routes')
const OrderRouter = require('./order.routes')
const PaymentRouter = require('./payment.routes')

router.use('/auth', authRouter)
router.use('/product', productRouter)
router.use('/category', categoryRouter)
router.use('/brand', brandRouter)
router.use('/user', userRouter)
router.use('/reviews', ReviewRouter)
router.use('/cart', CartRouter)
router.use('/sales', salesRouter)
router.use('/order', OrderRouter)
router.use('/payment', PaymentRouter)

module.exports = router