# docker-compose.yml


version: '3.8'

services:


  postgres:

    image: postgres:13.5

    restart: always

    environment:

      - POSTGRES_USER=process.env.DB_user

      - POSTGRES_PASSWORD=process.env.DB_pass

    volumes:

      - postgres:/var/lib/postgresql/data

    ports:

      - '5432:5432'


volumes:

  postgres: