let name = "Michael";
let check = false;
let number = undefined;
let none = null;
let a, b, c, d;
console.log(typeof(name), typeof(check), typeof(number), typeof(none));
let myAge = 25;
let yourAge = 30;
console.log("I am " + myAge + " years old.");
console.log("You are " + yourAge + " years old.");