data<-read.csv(file.choose())
attach(data)
split_data = select(data, KhoiA, KhoiB, KhoiC) %>% head(100000)
into_group = stack(split_data)
remove_na = na.omit(into_group)
colnames(remove_na)<-c('Diem', 'KhoiThi')
write.csv(remove_na, "..\\Lab2\\VN_highschool_exam_2018.csv", row.names = FALSE)
clean_data<-read.csv(file.choose())
attach(clean_data)
leveneTest(Diem, KhoiThi, center = mean)