let challenge = "30 Days Of JavaScript";
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toUpperCase());
console.log(challenge.toLowerCase());
console.log(challenge.substr(0, 1));
console.log(challenge.substring(3, challenge.length));
console.log(challenge.includes("Script"));
console.log(challenge.split());
console.log(challenge.split(" "));
let company = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
console.log(company.split(','));
console.log(challenge.replace("JavaScript", "Python"));
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt("J"));
console.log(challenge.indexOf("a"));
console.log(challenge.lastIndexOf("a"));
let sentence17 = 'You cannot end a sentence with because because because is a conjunction';
console.log(sentence17.indexOf("because"));
let sentence20 = ' 30 Days Of JavaScript ';
console.log(sentence20.trim());
console.log(challenge.startsWith("3"));
console.log(challenge.endsWith("t"));
console.log(challenge.match("a"));
let concat = '30 Days of';
console.log(concat.concat(' JavaScript'));
console.log(challenge.repeat(2));